trigger:
  branches:
    include:
    - main
  paths:
    include:
    - manifest.json
    - src/*
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: git
    name: internal/dotnet-versions

variables:
- template: variables/common.yml

stages:
- template: ../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
    linuxAmdBuildJobTimeout: 210
    customBuildInitSteps:
    - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
